Update runner.yml - test more steps
added 2 jobs to check the logs

diff --git a/.github/workflows/runner.yml b/.github/workflows/runner.yml
--- a/.github/workflows/runner.yml
+++ b/.github/workflows/runner.yml
@@ -8,7 +8,7 @@ on:
   workflow_dispatch:
 
 jobs:
-  test:
+  test-passed:
     runs-on: self-hosted
     steps:
       - uses: actions/checkout@v4
@@ -17,4 +17,16 @@ jobs:
 
       - name: Show path
         run: pwd
-  
+
+  test-failed:
+    runs-on: self-hosted
+    steps:
+      - name: Failed test
+        run: exit 1
+        continue-on-error: true
+
+      - name: Next test
+        run: echo "Run second test even the first failed"
+
+      - name: Check node.js version
+        run: node -v
